### ISSUE TITLE
Nao consigo mandar os arquivos

### ISSUE THREAD

**Issue by BruceMustache** [gilmarlnx/periodic-table#1]
Libera ai gilmaaaar!

████████████████████████████████████████
███▓███████▓▓╬╬╬╬╬╬╬╬╬╬╬╬▓███▓▓▓▓█▓╬╬╬▓█
███████▓█████▓▓╬╬╬╬╬╬╬╬▓███▓╬╬╬╬╬╬╬▓╬╬▓█
████▓▓▓▓╬╬▓█████╬╬╬╬╬╬███▓╬╬╬╬╬╬╬╬╬╬╬╬╬█
███▓▓▓▓╬╬╬╬╬╬▓██╬╬╬╬╬╬▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
████▓▓▓╬╬╬╬╬╬╬▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
███▓█▓███████▓▓███▓╬╬╬╬╬╬▓███████▓╬╬╬╬▓█
████████████████▓█▓╬╬╬╬╬▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬█
███▓▓▓▓▓▓▓╬╬▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
████▓▓▓╬╬╬╬▓▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
███▓█▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
█████▓▓▓▓▓▓▓▓█▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
█████▓▓▓▓▓▓▓██▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
█████▓▓▓▓▓████▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
████▓█▓▓▓▓██▓▓▓▓██╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
████▓▓███▓▓▓▓▓▓▓██▓╬╬╬╬╬╬╬╬╬╬╬╬█▓╬▓╬╬▓██
█████▓███▓▓▓▓▓▓▓▓████▓▓╬╬╬╬╬╬╬█▓╬╬╬╬╬▓██
█████▓▓█▓███▓▓▓████╬▓█▓▓╬╬╬▓▓█▓╬╬╬╬╬╬███
██████▓██▓███████▓╬╬╬▓▓╬▓▓██▓╬╬╬╬╬╬╬▓███
███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬████
███████▓▓██▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓████
████████▓▓▓█████▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█████
█████████▓▓▓█▓▓▓▓▓███▓╬╬╬╬╬╬╬╬╬╬╬▓██████
██████████▓▓▓█▓▓▓╬▓██╬╬╬╬╬╬╬╬╬╬╬▓███████
███████████▓▓█▓▓▓▓███▓╬╬╬╬╬╬╬╬╬▓████████
██████████████▓▓▓███▓▓╬╬╬╬╬╬╬╬██████████
███████████████▓▓▓██▓▓╬╬╬╬╬╬▓███████████﻿
████████████████████████████████████████
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░░░░████░░░░░░░░░░░░░░░░░░░░░░
░░░░░░░░░█████████░░░░░░░░░░░░░░░░░░░░
░░░░░░░░███░░░░░░█░░░░░░░░░░░░░░░░░░░░
░░░░░░███░░░░░░░░██░░░░░░░░░░░░░░░░░░░
░░░░░██░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░
░░░░██░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
░░░░█░░░░░░░░░░█░░░█░░░░░░░░░░░░░░░░░░
░░░███░█░░░░░██░█░░█░░░░░░░░░░░░░░░░░░
░░░███░██░░█░███░░░█░░░░░░░░░░░░░░░░░░
░░░██░██░░░█░███░░░█░░░░░░░░░░░░░░░░░░
░░█░░░██░░░░░░░░░░█░░░░░░░░░░░░░░░░░░░
░█░░░█░█░░░█░░██░░█░░░░░░░░░░░░░░░░░░░
░█░░░░███░░░░██░░░░█░░░░░░░░░░░░░░░░░░
░██░░░░░░░░██░██░░░█░░░░░░░░░░░░░░░░░░
░██████████████░░░░█░░░░░░░░░░░░░░░░░░
░█░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░██░░░
░█░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░██░█░░
███░░░░░░░░░░░░░░░░█░░░░░░░░░░░░█░░██░
██░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░█░░░█░
██░░░░░░░░░░░░░█░░██░░░░░░░░░░░██░░░█░
██░░░░░░░░░░░█░█░░░█░░░░░░░░░░░██░░░█░
██░░░░░░░░░░░█░█░░░█░░░░░░░░░░██░░░██░
██░░░░░░░░░░░█░█░░░█░░░░░░░░░░█░░░██░░
██░░░░░░░░░░░█░█░░░████████████░░░█░░░
██░░░░░░░░░░░█░█░░░███░░░░░░█░░░░██░░░
░█░░░░░░░░░░░█░█░░░█░░░██░░░░█░░░███░░
░█░░░░░░░░░░░█░█░░░█░░░░░█████░░░░░██░
░██░░░░░░░░░░█░█░░░░░░███░░░███░░░░░█░
░██░░░░░░░░░░█░█░░░░░░░░░░░░░███░░███░
░█░░░░░░░░░░░█░███░░░░░░░░░░░░░██░░░█░
░██░░░░░░░░██░░░░█░░░░░░██░░░░░░█░░░██
░░█░░░░░░░░█░░░░██░░░░░░░░░░░░░░██░░░█
░░██░░░░░░░███████░░░░░░░░░░░░░░█████░
░░░██░░░░░░░░███░░░░░░░██░░░░░░░█░░░░░
░░░██░░░░░░░░░░░░░░░░░█░░░░░░░░░█░░░░░
░░░░██░░░░░░░░░░░░░░░░░░█░░░░░░██░░░░░
░░░░░██░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░
░░░░░░██░░░░░░░░░░░░░░░░░░░░███░░░░░░░
░░░░░░░░██░░█░░░░░░░░░░░░░░██░░░░░░░░░
░░░░░░░░░█████░░█░░░░░███████░░░░░░░░░
░░░░░░░░███░░████████░█░░░░░░░░░░░░░░░
░░░░░░░░███░░░░░░░░█░██░░░░░░░░░░░░░░░
░░░███░████░░░░░██░█░░█░░░░░░░░░░░░░░░
░░░█░███░█░░░░░░████░█░░░░░░░░░░░░░░░░
░░░░█░░░░█░░░░░░█░░░░█░░░░░░░░░░░░░░░░
░░░░██░░██░░░░░░██░░░█░░░░░░░░░░░░░░░░
░░░░█████░░░░░░░░██░░█░░░░░░░░░░░░░░░░
░░░░░░░█░░░░░░░░░░███░░░░░░░░░░░░░░░░░

**Comment by gilmarodp** [comment]
> Libera ai gilmaaaar!
> 
> ████████████████████████████████████████
> ███▓███████▓▓╬╬╬╬╬╬╬╬╬╬╬╬▓███▓▓▓▓█▓╬╬╬▓█
> ███████▓█████▓▓╬╬╬╬╬╬╬╬▓███▓╬╬╬╬╬╬╬▓╬╬▓█
> ████▓▓▓▓╬╬▓█████╬╬╬╬╬╬███▓╬╬╬╬╬╬╬╬╬╬╬╬╬█
> ███▓▓▓▓╬╬╬╬╬╬▓██╬╬╬╬╬╬▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> ████▓▓▓╬╬╬╬╬╬╬▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> ███▓█▓███████▓▓███▓╬╬╬╬╬╬▓███████▓╬╬╬╬▓█
> ████████████████▓█▓╬╬╬╬╬▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬█
> ███▓▓▓▓▓▓▓╬╬▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> ████▓▓▓╬╬╬╬▓▓▓▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> ███▓█▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> █████▓▓▓▓▓▓▓▓█▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█
> █████▓▓▓▓▓▓▓██▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
> █████▓▓▓▓▓████▓▓▓█▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
> ████▓█▓▓▓▓██▓▓▓▓██╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬██
> ████▓▓███▓▓▓▓▓▓▓██▓╬╬╬╬╬╬╬╬╬╬╬╬█▓╬▓╬╬▓██
> █████▓███▓▓▓▓▓▓▓▓████▓▓╬╬╬╬╬╬╬█▓╬╬╬╬╬▓██
> █████▓▓█▓███▓▓▓████╬▓█▓▓╬╬╬▓▓█▓╬╬╬╬╬╬███
> ██████▓██▓███████▓╬╬╬▓▓╬▓▓██▓╬╬╬╬╬╬╬▓███
> ███████▓██▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬████
> ███████▓▓██▓▓▓▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓████
> ████████▓▓▓█████▓▓╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬▓█████
> █████████▓▓▓█▓▓▓▓▓███▓╬╬╬╬╬╬╬╬╬╬╬▓██████
> ██████████▓▓▓█▓▓▓╬▓██╬╬╬╬╬╬╬╬╬╬╬▓███████
> ███████████▓▓█▓▓▓▓███▓╬╬╬╬╬╬╬╬╬▓████████
> ██████████████▓▓▓███▓▓╬╬╬╬╬╬╬╬██████████
> ███████████████▓▓▓██▓▓╬╬╬╬╬╬▓███████████﻿
> ████████████████████████████████████████
> ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
> ░░░░░░░░░░░░████░░░░░░░░░░░░░░░░░░░░░░
> ░░░░░░░░░█████████░░░░░░░░░░░░░░░░░░░░
> ░░░░░░░░███░░░░░░█░░░░░░░░░░░░░░░░░░░░
> ░░░░░░███░░░░░░░░██░░░░░░░░░░░░░░░░░░░
> ░░░░░██░░░░░░░░░░░██░░░░░░░░░░░░░░░░░░
> ░░░░██░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░░░
> ░░░░█░░░░░░░░░░█░░░█░░░░░░░░░░░░░░░░░░
> ░░░███░█░░░░░██░█░░█░░░░░░░░░░░░░░░░░░
> ░░░███░██░░█░███░░░█░░░░░░░░░░░░░░░░░░
> ░░░██░██░░░█░███░░░█░░░░░░░░░░░░░░░░░░
> ░░█░░░██░░░░░░░░░░█░░░░░░░░░░░░░░░░░░░
> ░█░░░█░█░░░█░░██░░█░░░░░░░░░░░░░░░░░░░
> ░█░░░░███░░░░██░░░░█░░░░░░░░░░░░░░░░░░
> ░██░░░░░░░░██░██░░░█░░░░░░░░░░░░░░░░░░
> ░██████████████░░░░█░░░░░░░░░░░░░░░░░░
> ░█░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░░██░░░
> ░█░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░██░█░░
> ███░░░░░░░░░░░░░░░░█░░░░░░░░░░░░█░░██░
> ██░░░░░░░░░░░░░░░░░█░░░░░░░░░░░░█░░░█░
> ██░░░░░░░░░░░░░█░░██░░░░░░░░░░░██░░░█░
> ██░░░░░░░░░░░█░█░░░█░░░░░░░░░░░██░░░█░
> ██░░░░░░░░░░░█░█░░░█░░░░░░░░░░██░░░██░
> ██░░░░░░░░░░░█░█░░░█░░░░░░░░░░█░░░██░░
> ██░░░░░░░░░░░█░█░░░████████████░░░█░░░
> ██░░░░░░░░░░░█░█░░░███░░░░░░█░░░░██░░░
> ░█░░░░░░░░░░░█░█░░░█░░░██░░░░█░░░███░░
> ░█░░░░░░░░░░░█░█░░░█░░░░░█████░░░░░██░
> ░██░░░░░░░░░░█░█░░░░░░███░░░███░░░░░█░
> ░██░░░░░░░░░░█░█░░░░░░░░░░░░░███░░███░
> ░█░░░░░░░░░░░█░███░░░░░░░░░░░░░██░░░█░
> ░██░░░░░░░░██░░░░█░░░░░░██░░░░░░█░░░██
> ░░█░░░░░░░░█░░░░██░░░░░░░░░░░░░░██░░░█
> ░░██░░░░░░░███████░░░░░░░░░░░░░░█████░
> ░░░██░░░░░░░░███░░░░░░░██░░░░░░░█░░░░░
> ░░░██░░░░░░░░░░░░░░░░░█░░░░░░░░░█░░░░░
> ░░░░██░░░░░░░░░░░░░░░░░░█░░░░░░██░░░░░
> ░░░░░██░░░░░░░░░░░░░░░░░░░░░░░██░░░░░░
> ░░░░░░██░░░░░░░░░░░░░░░░░░░░███░░░░░░░
> ░░░░░░░░██░░█░░░░░░░░░░░░░░██░░░░░░░░░
> ░░░░░░░░░█████░░█░░░░░███████░░░░░░░░░
> ░░░░░░░░███░░████████░█░░░░░░░░░░░░░░░
> ░░░░░░░░███░░░░░░░░█░██░░░░░░░░░░░░░░░
> ░░░███░████░░░░░██░█░░█░░░░░░░░░░░░░░░
> ░░░█░███░█░░░░░░████░█░░░░░░░░░░░░░░░░
> ░░░░█░░░░█░░░░░░█░░░░█░░░░░░░░░░░░░░░░
> ░░░░██░░██░░░░░░██░░░█░░░░░░░░░░░░░░░░
> ░░░░█████░░░░░░░░██░░█░░░░░░░░░░░░░░░░
> ░░░░░░░█░░░░░░░░░░███░░░░░░░░░░░░░░░░░

Clique aqui:
https://github.com/gilmarlnx/periodic-table/invitations
